%% Setup Drone
m = 0.2
I = [[0.1,0,0];[0,0.1,0];[0,0,0.08]]

% sample time
ts = 0.01

% Initial States (Initial XYZ is generated by XYZsignal script)
Euler_0 = [0;0;0]

% XYZ_0 should not be [0;0;0] because the initial target point is set to
% [0;0;0]
XYZ_0 = [1;2;0]
body_rate_0 = [0;0;0]

% Set surround rate (if 0: follow mode; if 0.5: surround mode)
surround_rate = 1

% Environment
g = [0;0;-9.8]
